apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alderaan.fullname" . }}-config
  labels:
    {{- include "alderaan.labels" . | nindent 4 }}
data:
  # Server Configuration
  SERVER_PORT: {{ .Values.config.server.port | quote }}
  GIN_MODE: {{ .Values.config.server.ginMode | quote }}

  # Database Configuration
  DB_HOST: {{ include "alderaan.databaseHost" . | quote }}
  DB_PORT: {{ include "alderaan.databasePort" . | quote }}
  DB_NAME: {{ include "alderaan.databaseName" . | quote }}
  DB_USER: {{ include "alderaan.databaseUsername" . | quote }}
  DB_SSL_MODE: {{ .Values.config.database.sslMode | default "require" | quote }}
  DB_MAX_OPEN_CONNS: {{ .Values.config.database.maxOpenConns | default "25" | quote }}
  DB_MAX_IDLE_CONNS: {{ .Values.config.database.maxIdleConns | default "25" | quote }}
  DB_CONN_MAX_LIFETIME: {{ .Values.config.database.connMaxLifetime | default "5m" | quote }}

  # Logging Configuration
  LOG_LEVEL: {{ .Values.config.logging.level | default "info" | quote }}
  LOG_FORMAT: {{ .Values.config.logging.format | default "json" | quote }}

  # Monitoring Configuration
  METRICS_ENABLED: {{ .Values.config.metrics.enabled | default "true" | quote }}
  METRICS_PATH: {{ .Values.config.metrics.path | default "/metrics" | quote }}

  # Health Check Configuration
  HEALTH_CHECK_PATH: {{ .Values.config.healthCheck.path | default "/health" | quote }}

  # Graceful Shutdown Configuration
  SHUTDOWN_TIMEOUT: {{ .Values.config.gracefulShutdown.timeout | default "30s" | quote }}
