apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alderaan.fullname" . }}
  labels:
    {{- include "alderaan.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "alderaan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if not .Values.postgresql.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "alderaan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alderaan.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.server.port | int }}
              protocol: TCP
          env:
            # Environment variables from ConfigMap
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: SERVER_PORT
            - name: GIN_MODE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: GIN_MODE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: DB_USER
            - name: DB_SSL_MODE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: DB_SSL_MODE
            - name: DB_MAX_OPEN_CONNS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: DB_MAX_OPEN_CONNS
            - name: DB_MAX_IDLE_CONNS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: DB_MAX_IDLE_CONNS
            - name: DB_CONN_MAX_LIFETIME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: DB_CONN_MAX_LIFETIME
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: LOG_LEVEL
            - name: LOG_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: LOG_FORMAT
            - name: METRICS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: METRICS_ENABLED
            - name: METRICS_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: METRICS_PATH
            - name: HEALTH_CHECK_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: HEALTH_CHECK_PATH
            - name: SHUTDOWN_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "alderaan.fullname" . }}-config
                  key: SHUTDOWN_TIMEOUT
            # Database password from secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "alderaan.databaseSecretName" . }}
                  key: {{ include "alderaan.databaseSecretPasswordKey" . }}
            {{- with .Values.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.config.healthCheck.path | default "/health" }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 3 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.config.healthCheck.path | default "/health" }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 3 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
