---
name: Package and Publish Helm Chart

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: 'v3.13.0'

    - name: Configure Helm
      run: |
        echo ${{ secrets.USER_TOKEN }} | helm registry login -u ${{ github.actor }} --password-stdin ghcr.io

    - name: Package Helm Chart
      run: |
        helm package ./charts/alderaan --destination ./packages

    - name: Push Helm Chart to GitHub Packages
      run: |
        helm push ./packages/alderaan-*.tgz oci://ghcr.io/${{ github.repository_owner }}/helm-charts
